### ISSUE TITLE
unlisted missing dependencies

### ISSUE THREAD

**Issue by kayky21** [lolieg/CruiserVolumeControl#1]
[Error  :   BepInEx] Could not load [CruiserVolumeControl 1.0.0] because it has missing dependencies: BMX.LobbyCompatibility

**Comment by lolieg** [comment]
Hey, sorry about that. I will just remove the dependency completely when I'm home. It just was pre configured in the template I used😭

**Comment by lolieg** [comment]
Ok, should be fixed. The update will appear after some time.
